spring.application.name=semantic-search
spring.ai.openai.api-key=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
spring.ai.openai.chat.model=gpt-4o-mini

# Database configuration
spring.datasource.url = jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username = postgres
spring.datasource.password = postgres
